# syntax=docker/dockerfile:1

# Build the application from source
FROM golang:1.19 AS build-stage

WORKDIR /app
#  COPY go.mod go.sum ./
COPY . .

WORKDIR /app/go-modules

RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/app

# Run the tests in the container
FROM build-stage AS run-test-stage
RUN go test -v ./...

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /root

# COPY --from=build-stage /docker-gs-ping /docker-gs-ping
COPY --from=build-stage /app/app .
EXPOSE 8080

USER nonroot:nonroots

CMD ["/app"]